### ISSUE TITLE
Why use k-neighbor classifier instead of SVC classifier   

### ISSUE THREAD

**Issue by flyudvik** [teimurjan/digits-recognizer#1]
The results of the demo site is very poor. Possible solutions are:
* filter out white spaces around image (cropping borders) in image transformation utils
* use convolutional neural network model

The tutorial shows another approach using the image data for training and another classifier 
http://scikit-learn.org/stable/auto_examples/classification/plot_digits_classification.html

**Comment by teimurjan** [comment]
It was made in order to practice especially with the knn. I planed to add the choice whether to use svc or knn later. Thanks for the tutorial, I think it will help me improve the quality of my classifier.

**Comment by teimurjan** [comment]
@flyudvik checkout my latest commit ab78872731e133a317f8cc86a38e9c1ed0857629. I fixed a bug with reducing the intensity of an image and added cropping of the white frame. I think your suggestion about the filtering white spaces was too helpful. I think the quality of my classifier is much better now. Thanks!
